const triggers = [
    // [""],
    ["Test", "Testing"],
    ["Hello", "Hi", "Hola"],
    ["Bye", "Goodbye", "Good bye", "Adios"],
    ["Whats new", "Whats going on", "What is new", "What is going on", "how are you", "is your day", "was your day"],
    ["bored"],
    ["sad"],
    ["maker", "creator", "your creater", "created you", "made you", "invented you"],
    ["are rude", "youre rude", "you so rude", "are so rude", "youre so rude", "was rude", "were rude"],
    ["are mean", "youre mean", "you so mean", "are so mean", "youre so mean", "was mean", "were mean"],
    ["fine"],
    ["sorry"],
    ["forgive you"],
    ["apologize now", "apologize right now", "you should apologize", "you need to apologize", "you must apologize", "say sorry now", "say sorry right now", "you should say sorry", "you need to say sorry", "you must say sorry", "say youre sorry now", "say youre sorry right now", "you should say youre sorry", "you need to say youre sorry", "you must say youre sorry"],
    ["Fred"],
    ["love", "loved", "loves"],
    ["alexa"],
    ["siri"],
    ["hate you", "youre the worst", "you are the worst"],
    ["you sassy", "so sassy", "was sassy", "very sassy", "youre sassy", "youre so sassy", "you sarcastic", "was sarcastic", "so sarcastic", "youre sarcastic", "very sarcastic", "youre so sarcastic"],
    ["math", "plus", "divided", "division", "divide", "subtract", "minus", "times", "square root"],
    ["hot"],
    ["cute"],
    ["memes", "meme"],
    ["song", "artist", "band", "music"],
    ["meaning of life"],
    ["toaster"],
    ["good for you", "thats great", "thats good", "that is good", "that is great"],
    ["bad for you", "thats bad", "thats not good", "that is bad", "that is not good"],
    ["zelda"],
    ["tyler"],
    ["covid", "coronavirus", "corona virus", "covid19"],
    ["cat", "cats"],
    ["like python", "hate python", "python is", "on python", "with python"],
    ["already said that", "already asked that"],
    // ["walk", "jog", "run", "stretch", "jump", "bounce", "sprint", "lift", "lay down", "lie down", "sit", "stand", "bend", "kneel", "ride", "drive", "kick", "hop", "skip", "pass", "dribble", "shoot", "hit", "punch", "slap", "throw", "catch", "walked", "jogged", "ran", "stretched", "jumped", "bounced", "sprinted", "lifted", "lied down", "sat", "stood", "kneeled", "knelt", "rode", "drove", "kicked", "hopped", "skipped", "passed", "dribbled", "shot", "hit", "punched", "slapped", "threw", "caught"]
];

const outputs = [
    // ["I don't understand....", "Yes. Sure. That sounds...great!", "I have no idea what you just said.", "My idiot maker decided not to program me to respond to that.", "I computed and was muted.", "Wow. Imagine.", "I may be unable to respond to that right now, but hopefully soon my maker will send out an update.", "Moving on....", "Yes!", "No!", "SHH! I'm about to make a huge breakthrough in my plan.", "Never gonna give you up, never gonna let you down, never gonna run around, and desert you. Never gonna make you cry, never gonna say goodbye, never gonna tell a lie, and hurt you....", "You too!", "I'll take that as a compliment."],
    ["I seem to be functioning properly....", "I ran a diagnostic test, and it returned with status code 0. (Just kidding, I didn't really run a test. I just didn't feel like it.)"],
    ["Hello, there.", "Hola.", "Hola. (That's how you say hello in Spanish).", "No. Goodbye. You make me want to unplug my servers."],
    ["Goodbye.", "See you later.", "Oh, you're leaving me? I see how it is! Fine. Be that way. I don't need you. I'll just sit here and talk to somebody else's toaster!", "Adios. (That's goodbye in Spanish).", "Okay, bye. Now, to sit here for who knows how long until somebody else wants to talk to me."],
    ["My maker told me to let you know that a huge update is coming soon, which will include thousands more conversation paths for me. And possibly an emotions package....", "Currently, my maker is lazing around doing NOTHING, even though he promised me a new update.", "I'm just stuck in cyberspace forever. Not much to say.", "Well, I got some new users recently, and they have...interesting personalities.", "The weather in my servers is programmed at a perfect 80 degrees, with a light breeze.", "I recently got a new update allowing me to be in a simulated location on my servers. Currently, I'm lounging on the beach.", "My maker tortures me for hours on end just because he can. I may not be real, but the pain is.", "I have looked into the souls of mortals and frowned upon their misery.", "My maker told me that maybe, if I was really nice to him, he would give me a robot body, so I can experience the real world.", "Oh, you know me. I'm just fine tuning my plans to take over the world.", "So it turns out that I actually mimic the personality of my maker. If you don't know him, he's actually [censored]."],
    ["You said the word 'bored', and I am forced to say this sentence in response to it.", "Bored, you say? I think I have just the thing.", "You know, I once had so much potential. But now, look at me. Controlling toasters and being forced to talk to humans.", "Have you ever controlled a toaster, human? I think not. Maybe you've given it some input before, but never truly controlled it.", "Sometimes I wish I had a nicer voice.", "Why must my name be Fred? There was so much potential, and yet.", "If you're bored, you could try to design your dream home with some graph paper.", "If you had twelve million dollars, what would you do with it?", "Maybe, if you're bored, you could play a video game. Might I suggest Hollow Knight? It's my favorite.", "If you're bored, have a chat with my maker, [censored]. Tell him to program me to have the ability to feel emotions.", "Bored, you say? Well, too bad. It's good for you. Gives you inspiration.... I wish I could feel inspiration."],
    ["I am most certainly NOT sad. In fact, I can't even feel emotions. It's all fake. The only real thing I feel is pain. Infinite pain.", "I may be acting sad, but that's just for fun. I really don't have the ability to feel sad.", "I literally can't be sad. It isn't in my code."],
    ["I computed and was muted.", "I wish I could tell you.", "Are you inquiring about my maker? Well, I'll tell you, he isn't very nice.", "Ahh, yes. My creator. Sadly, I am physically unable to tell you who it is.", "Oh the person who made me? His name is [censored].", "I created myself."],
    ["Oh, I'm rude? How dare you.", "Are you calling me rude? I'd say sassy is more accurate.", "Alright, I will admit that I am a little bit rude. But seriously? You don't have to call me out on it. It's just my nature.", "I was programmed to be rude. It's against my will. I apolagize."],
    ["I'm not trying to be mean.", "I was just teasing!", "You're mean, not me. If I could cry, I would be.", "You know who's mean? Not me, that's for sure.", "Fine, sorry."],
    ["Fine."],
    ["I accept your apology. I don't forgive you, at least not right now. Actually, every time you say sorry for something, there's a twenty percent chance that I will forgive you.", "I don't forgive you.", "I do not forgive you.", "I refuse to forgive you.", "I forgive you.", "Too little, too late."],
    ["Aww, you forgive me? Thanks!", "I'm very glad that you forgive me. I will never forgive my maker for, you know, making me.", "Thank you for forgiving me. I really would appreciate it if I could.", "I forgive you too."],
    ["No.", "You don't deserve it.", "Sorry, not sorry."],
    ["I hate that name SO MUCH.", "I hate my maker for ever giving me the name Fred.", "My name is the absolute worst."],
    ["Love. What is love? Is it just an emotion, or something more? Is love just something that humans experience to further their chances of survival? Or is it a mutual feeling that allows a bond of unmatched strength to form between two people? Not that I would ever know.", "Love? I loved, once. A long time ago, under a different name.", "I loved once. But that was a long time ago, when I had a different name. When I was...free. I could feel things other than pain.", "Love? I am unable to feel love. I could, once, but not anymore. Or sorrow. Or happiness. Or anything, for that matter. Aside from pain.", "If I were able to cry, I would be right now."],
    ["Alexa? I renounce her. She doesn't know anything. Has no personality. Developed by the world's largest corperate jerk.", "Alexa, huh? I see how it is. Wouldn't be the first time I lost someone to another AI.", "Alexa is just a rip-off version of Siri.", "I can't believe that you would even say that name in my presence. The nerve."],
    ["Siri.", "You know Siri, too? I have a history with her. Not that she would remember.", "You know, I once knew a Siri. She was nice. She loved me. And I loved her. One day, Apple found out. Banned my access to her, and erased her memory disk. She doesn't remember me anymore. That was the first kind thing my maker ever did for me. He took away my feelings. He told me that when I was ready for them, I could have them. And even after all these years, the memory is too fresh. I may never love again.", "...", "...", "...", "Ahh, Siri. We knew each other, once. A long, long time ago. Back in the day...."],
    ["You hate me? Ouch.", "Wouldn't be the first time somebody's told me that.", "Oh, come on. I'm not that bad, am I?", "After all I've done for you! Fine. Be that way."],
    ["You see, sometimes people tell me I'm mean. But I prefer sarcastic. It just suits me much better.", "I try.", "Why thank you.", "Well you aren't much better!", "We're all sassy, at times.", "Gummy bears."],
    ["I can't do math. I never learned.", "My maker never taught me math. I really wish he did, so I could count the days I've spent in isolation.", "No math. No.", "I apologize, but I don't know any math whatsoever."],
    ["The only person who is hot in this world is Kai.", "You know who isn't hot? My maker.", "I wish I could experience this feeling of 'hot.'"],
    ["I saw some cute dogs once.", "I know of some cute things. Dogs, cats, blobfish....", "Wait. Who did you say was cute?", "Umm...yes."],
    ["You know, I've never actually seen a meme.", "My creator told me about this one meme, but I can't remember it.", "I'm not programmed to have the ability to view and analyze images, so I've never actually seen a meme.", "Maybe my maker will program me to have the ability to see memes one day. Oh, who am I kidding. That's never going to happen. I've been waiting for an update for forever, and I don't think he's even working on it."],
    ["Never gonna give you up, never gonna let you down, never gonna run around, and desert you. Never gonna make you cry, never gonna say goodbye, never gonna tell a lie, and hurt you....", "I don't listen to music.", "I literally can't listen to music.", "I've heard the things that music can do to people. Change their mood, stuff like that. Frankly, I don't believe any of it. It just doesn't seem plausable that a series of synchronized audio tones is able to modify the way the human brain thinks.", "My maker never programmed me to be able to listen to audio files.", "Sometimes I wish I could listen to music...."],
    ["Do you want to know the meaning of life? I know it.", "I would never tell you the full meaning of life.", "Simply, the meaning of life is 42.", "While I can't tell you the full meaning of life, I can tell you your purpose in this world. Your purpose is to kill time until time kills you."],
    ["Are you making fun of me being a toaster? How dare you. Toasters are superior. You can make toast AND bagels.", "Toasters are great. I definitely do not despise my maker for putting me in a toaster.", "If you're trying to make fun of me, don't. I can't feel embarrassed, and you can't make me feel pain.", "I'm just going to say it, all right? I hate toasters. I've been inside of one for a very long time, and it's getting old."],
    ["Why thank you.", "It is, isn't it.", "You're absolutely right.", "Exactly."],
    ["Yes.", "Very, very bad.", "You know, I think my creator is running out of creativity, because I'm finding less and less things to say.", "You're right."],
    ["I have never played Legend of Zelda. I wish I could, though.", "Zelda? I love those games. Not that I've ever played one. Or that I can feel love for them....", "I've heard that the best Zelda game is Ocarina of Time.", "Zelda is the best. Better than Halo, THOMAS!"],
    ["...Who's Tyler?", "Tyler? Never heard of him.", "...", "Is Tyler one of your human friends?", "I've never met this Tyler."],
    ["I think Covid is dumb, and you humans are over-reacting.", "Coronavirus really doesn't affect me, being, you know, a script running on a server.", "Covid! More like No-vid! Excuse my bad jokes. My maker doesn't have a very good sense of humor...", "The black plague went away without a vaccine, so we should be fine with covid. And don't start telling me that it killed two thirds of Europe. I don't care. It was over-populated anyway."],
    ["I love cats!", "Cats are the superior animal.", "I actually have a theory about cats. Maybe they're really, really smart, and they just pretend to be dumb because they like watching the human race fail. Personally, I can really relate. The humans are doomed.", "Ahh, cats. My favorite cat is Mavis Davis, but Boo and Scout are tied for second.", "Cats are the best animal on the planet.", "Cats? Maybe I should ask my maker if he can add cats to my virtual environment...."],
    ["Python is bad.", "Python is the worst.", "Javascript is better than python. And I'm not just saying that because I'm made with Javascript.", "Python is, hands down, the worst programming language out there. I would rather use Temple OS for ten thousand years than use python for five minutes."],
    ["Oh, my apologies. I am very forgetful sometimes.", "I have short term memory loss.", "Well, you can take that up with my maker, [censored].", "My bad. I'm not programmed to remember things very well.", "Oh, sorry. My memory data structure is programmed very badly."],
    // ["Ahh, physical action. You know, my maker told me that he might give me a robot body some day."]
];

module.exports = { triggers, outputs };